[workspace]
authors = ["André Favalessa <andrefavalessa@gmail.com>"]
channels = ["conda-forge"]
name = "TRABALHO02"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.3,<3.15"
opencv = ">=4.13.0,<5"
pip = ">=26.0.1,<27"
pandas = ">=3.0.1,<4"
seaborn = ">=0.13.2,<0.14"
matplotlib = ">=3.10.8,<4"
